# syntax=docker/dockerfile:1
services:
  redis:
    container_name: redis
    image: redis:7.4-bookworm
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - type: bind
        source: /xblock/redis
        target: /var/redis

  firehose:
    container_name: firehose
    image: aendra/xblock-processor:latest
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: npm run firehose

  worker:
    container_name: worker
    image: aendra/xblock-processor:latest
    depends_on:
      - redis
      - queue
    command: npm run worker

  dashboard:
    container_name: dashboard
    image: cjlapao/rq-dashboard:latest
    environment:
      - RQ_DASHBOARD_BIND=0.0.0.0
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - 9181:9181
